[workspace]
resolver = "3"

members = [
	"crates/bile-math",
	"crates/bile-tiles",
	"crates/bile-scene",
	"crates/bile-scene-source",
	"crates/bile-region-loader",
	"crates/bile",
	"crates/bile-demo-app",
]

default-members = [
	"crates/bile-demo-app",
]

[profile.release]
debug = true

[workspace.dependencies]
bevy = "0.19"
bevy_ecs = "0.19"
bevy-trait-query = "0.19.0"
crossbeam-channel = "0.5.15"
wgpu = "29.0.3"
serde = "1.0.229"
log = "0.4"
num = "0.4.3"
bytemuck = { version = "1.24", features = ["derive"] }
bitflags = "2.13"
tracy-client = { version = "0.18.4", default-features = false }
rustc-hash = "2.1.2"
tokio = "1"
futures = "0.3.32"
bile-math = { version = "0.1.0", path = "crates/bile-math" }
bile-tiles = { version = "0.1.0", path = "crates/bile-tiles" }
bile-scene = { version = "0.1.0", path = "crates/bile-scene" }
bile-scene-source = { version = "0.1.0", path = "crates/bile-scene-source" }
bile-region-loader = { version = "0.1.0", path = "crates/bile-region-loader" }
bile = { version = "0.1.0", path = "crates/bile" }

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"
collapsible_if = "allow"
